### PR TITLE
angularify/angular-semantic-ui#29 Dropdown enhancements

### PR DESCRIPTION
**Pull request by Kurmaev**
Simplify dropdown widget.
Add support for custom dropdown values.

### CODE REVIEW

**Comment by jspdown** [comment]
Thanks @Kurmaev. Your patch simplify clearly the dropdown component! 
Could you please update  `src/dropdown/test/spec.js` and `src/dropdown/docs/demo.html` files ?

**Comment by Kurmaev** [comment]
@jspdown yes I planning to do it at weekend

**Comment by jspdown** [comment]
PR #37 ha been merged and improve some part of the `dropdown` components. Please, remember to update your local branch.

**Comment by Kurmaev** [comment]
@jspdown My code is rebased on top of master branch; some commits are squashed. Updated demo page and actualized test specs for it.

**Pull request merged**
