### PR TITLE
Resolve issue #22 where destroy listener was being called to destroy an ...

### PR DESCRIPTION
**Pull request by tombee**
...accordion in the dropdown module

Fix for issue #22 

Signed-off-by: Tom Barlow <tomwbarlow@gmail.com>

### CODE REVIEW

**Comment by jspdown** [comment]
Thanks @tombee !

**Comment by tombee** [comment]
Hi @jspdown!  Is there any plan to cut a new release soon?  Would love to get this fix into our code in shipyard :smile:

**Comment by jspdown** [comment]
@tombee, we can release a new one today. Do you use angular-semantic-ui on the whole application?

**Comment by tombee** [comment]
@jspdown There's one page where it was introduced, since the dropdown directive seems to work well when binding to a value inside an `ng-repeat`.  Will definitely be looking at using more of the directives in angular-semantic-ui elsewhere in the project though :smile:

**Pull request merged**
